MxOnline/MxOnline/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.views.static import serve

from MxOnline.settings import MEDIA_ROOT, MEDIA_URL, STATIC_ROOT#用于生产环境
import xadmin #导入xadmin工具包

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^', include('users.urls'), name="users"), #用户登录注册相关urls
    url(r'^', include('organization.urls'), name="organization"), #授课机构urls
    url(r'^', include('courses.urls'), name="courses"), #公开课url
    url(r'^captcha/', include('captcha.urls')), #生成验证码
    url(r'^admin/', include(xadmin.site.urls)), #这里使用xadmin来管理后台，替换原有的admin
    url(r'^ueditor/', include('DjangoUeditor.urls')),  # 富文本url
    url(r'^Banner/(?P<path>.*)$', serve, { 'document_root':MEDIA_ROOT }), #配置在生产环境下的图片不能访问的问题
    url(r'^static/(?P<path>.*)$', serve, { 'document_root':STATIC_ROOT }), #配置在生产环境下的静态样式不能访问的问题
] #+ static(MEDIA_URL, document_root=MEDIA_ROOT) #图片的url连接


#全局404, 500, 403 url配置
handler404 = "users.views.page_not_found"
handler500 = "users.views.page_error"
handler403 = "users.views.page_403error"

MxOnline/extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

MxOnline/apps/courses/models.py
from datetime import datetime

from DjangoUeditor.models import UEditorField

from django.db import models
from organization.models import CourseOrg, Teacher

# Create your models here.


'''课程详情的模型'''
class Coures(models.Model):
    course_org = models.ForeignKey(CourseOrg, null=True, blank=True, verbose_name="课程机构")
    name = models.CharField(max_length=50, verbose_name="课程名称")
    desc = models.CharField(max_length=300, verbose_name="课程描述")
    # detail = models.TextField(verbose_name="课程详情")
    detail = UEditorField(default='', width=600, height=300, toolbars="full", imagePath="course/image/%(basename)s_%(datetime)s.%(extname)s",
                          filePath="courses/file/%(basename)s_%(datetime)s.%(extname)s", settings={}, command=None, blank=True, verbose_name="课程详情")
    is_tg = models.BooleanField(default=False, verbose_name="课程首页推广")
    degree = models.CharField(choices=(("cj","初级"),("zj","中级"),("gj","高级")), default="zj", max_length=5, verbose_name="视频级别")
    learn_times = models.IntegerField(default=0, verbose_name="学习时长")
    students = models.IntegerField(default=0, verbose_name="学习人数")
    fav_nums = models.IntegerField(default=0, verbose_name="收藏人数")
    kcjs_org = models.ForeignKey(Teacher, null=True, blank=True, verbose_name="课程讲师")
    category = models.CharField(max_length=50, null=True, blank=True, verbose_name="课程类别")
    image = models.ImageField(upload_to="courses/%Y/%m", null=True, blank=True, verbose_name="封面图片")
    click_nums = models.IntegerField(default=0, verbose_name="点击人数")
    tag = models.CharField(default="Python开发", max_length=20, null=True, blank=True, verbose_name="课程标签")
    kcxz = models.CharField(max_length=50, null=True, blank=True, verbose_name="课程须知")
    xdaoshenm = models.CharField(max_length=100, null=True, blank=True, verbose_name="能学到什么？")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "课程详情"
        verbose_name_plural = verbose_name
        db_table = "Coures"

    #获取课程章节数
    def get_zj_nums(self):
        return self.lesson_set.all().count()
    get_zj_nums.short_description = "章节数" #定义这个函数在后台管理里面显示的名字

    #在后台里面加入html
    def htmls(self):
        from django.utils.safestring import mark_safe
        return mark_safe("<a href=\"http://www.baidu.com\">跳转一下</a>")
    htmls.short_description = "显示的html"

    #获取学习人数
    def get_learn_users(self):
        return self.usercourse_set.all()[:5]

    #获取课程的章节
    def get_zj(self):
        return self.lesson_set.all()

    #获取课程附件
    def get_kcfj(self):
        return self.courseresource_set.all()

    #获取当前课程的评论
    def get_pl(self):
        return self.coursecomments_set.all()

    def __str__(self):
        return self.name

'''获取首页轮播图的课程'''
class BannerCoures(Coures):

    class Meta:
        verbose_name = "轮播课程"
        verbose_name_plural = verbose_name
        proxy = True #这里非常关键如果不设置会新建一个表


'''课程章节数据模型'''
class Lesson(models.Model):
    course = models.ForeignKey(Coures, verbose_name="课程名称")
    name = models.CharField(max_length=120, verbose_name="章节名称")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "课程章节"
        verbose_name_plural = verbose_name
        db_table = "Lesson"

    #获取视频数据
    def get_spzy(self):
        return self.video_set.all()

    def __str__(self):
        return self.name


'''视频模型'''
class Video(models.Model):
    lesson = models.ForeignKey(Lesson, verbose_name="章节名称")
    name = models.CharField(max_length=120, verbose_name="视频名称")
    video_url = models.URLField(null=True, blank=True, verbose_name="视频资源地址")
    video_time = models.IntegerField(null=True, blank=True, verbose_name="视频时长")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="更新时间")

    class Meta:
        verbose_name = "视频资源"
        verbose_name_plural = verbose_name
        db_table = "Video"

    def __str__(self):
        return self.name

'''视频附件下载表模型'''
class CourseResource(models.Model):
    course = models.ForeignKey(Coures, verbose_name="课程名称")
    name = models.CharField(max_length=50, verbose_name="附件名称")
    download = models.FileField(upload_to="course/resource/%Y/%m", verbose_name="资源文件", max_length=150)
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "课程附件"
        verbose_name_plural = verbose_name
        db_table = "CourseResource"

    def __str__(self):
        return  self.name

MxOnline/apps/users/forms.py
from django import forms
from captcha.fields import CaptchaField #验证码

from users.models import UserProFile


#用户登陆
class Login_Form(forms.Form):
    username = forms.CharField(required=True, error_messages={"required":"账号不能为空"})
    password = forms.CharField(required=True, min_length=5,error_messages={"required": "密码不能为空",})


#用户账号注册
class RegisterForm(forms.Form):
    email = forms.EmailField(required=True, error_messages={"required":"邮箱不能为空"})
    password = forms.CharField(required=True, min_length=6, max_length=16, error_messages={"required":"密码不能为空"})
    captcha = CaptchaField(error_messages={"invalid":"验证码错误", "required":"验证码不能为空"}) #生成验证码

#用户找回密码
class ForgetPwdForm(forms.Form):
    email = forms.EmailField(required=True, error_messages={"required":"邮箱不能为空"})
    captcha = CaptchaField(error_messages={"invalid":"验证码错误", "required":"验证码不能为空"}) #生成验证码

#密码修改
class MoforPwdForm(forms.Form):
    password1 = forms.CharField(required=True, error_messages={"required": "密码不能为空"})
    password2 = forms.CharField(required=True, error_messages={"required": "密码不能为空"})

#用来修改用户中心的头像
class UploadImageForm(forms.ModelForm):
    class Meta:
        model = UserProFile
        fields = ['image']

#用来修改用户中心的信息
class UploadinfoForm(forms.ModelForm):
    class Meta:
        model = UserProFile
        fields = ['nick_name','birday','gender','address','mobile']

MxOnline/extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user
        
        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

MxOnline/templates/course-detail.html
{% extends 'base.html' %}
{% block title %}课程详情——基于Django的在线视频教学网站{% endblock %}
{% block custom_bread %}
    <section>
	<div class="wp">
		<div class="crumbs">
			<ul>
				<li><a href="/">首页</a>></li>
                <li><a href="{% url 'courses' %}">公开课程</a>></li>
				<li>课程详情</li>
			</ul>
		</div>
	</div>
</section>
{% endblock %}
{% block content %}
    {% load static %}
    <section>
	<div class="wp">
		<div class="groupPurchase_detail detail">
			<div class="toppro">
				<div class="left">
					<div class="picbox">
						<div class="tb-booth tb-pic">
							<img width="440" height="445" src="../../Banner/{{ course_cent.image }}" class="jqzoom" />
						</div>

					</div>
					<div class="des">
						<h1 title="django 从入门到精通体验开始了">{{ course_cent.name }}</h1>
						<span class="key">{{ course_cent.desc }}</span>
						<div class="prize">
							<span class="fl">难度：<i class="key">{{ course_cent.get_degree_display }}</i></span>
							<span class="fr">学习人数：{{ course_cent.students }}</span>
						</div>
						<ul class="parameter">
							<li><span class="pram word3">时&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;长：</span><span>{{ course_cent.learn_times }}</span></li>
                            <li><span class="pram word3">章&nbsp;节&nbsp;数：</span><span>{{ course_cent.get_zj_nums }}</span></li>
                            <li><span class="pram word3">课程类别：</span><span title="">{{ course_cent.category }}</span></li>
							<li class="piclist"><span class="pram word4">学习用户：</span>
                                     {% for user in course_cent.get_learn_users %}
                                    <span class="pic"><img width="40" height="40" src="../../Banner/{{ user.user.image }}"/></span>
                                    {% endfor %}

							</li>
						</ul>
						<div class="btns">
							<div class="btn colectgroupbtn" id="jsLeftBtn">
                                 {% if has_fav_course %}已收藏{% else %}收藏{% endif %}
                            </div>
                                <div class="buy btn"><a style="color: white" href="{% url 'course_video' course_cent.id %}">开始学习</a></div>
						</div>
					</div>
                    <div class="group-share-box">
                        <div class="bdsharebuttonbox"
                             data-text="django开始了"
                             data-desc="我在#慕课网#发现了"
                             data-comment=""
                             data-url="/group/groupdetail/15/">
                            <span class="fl">分享到：</span>
                            <a href="#" class="bds_more" data-cmd="more"></a>
                            <a title="分享到QQ空间" href="#" class="bds_qzone" data-cmd="qzone"></a>
                            <a title="分享到新浪微博" href="#" class="bds_tsina" data-cmd="tsina"></a>
                            <a title="分享到腾讯微博" href="#" class="bds_tqq" data-cmd="tqq"></a>
                            <a title="分享到人人网" href="#" class="bds_renren" data-cmd="renren"></a>
                            <a title="分享到微信" href="#" class="bds_weixin" data-cmd="weixin"></a>
                        </div>
                    </div>
				</div>
				<div class="right">
					<div class="head">
						<h1>授课机构</h1>
						<p>世界名校，课程权威</p>
					</div>
					<div class="pic">
                        <a href="{% url 'orghome' course_cent.course_org.id %}">
                            <img width="150" height="80" src="../../Banner/{{ course_cent.course_org.image }}"/>
                        </a>
                    </div>
					<a href="{% url 'orghome' course_cent.course_org.id %}">
                        <h2 class="center" title="{{ course_cent.course_org.name }}">{{ course_cent.course_org.name }}</h2>
                    </a>
					<div class="btn  notlogin"data-favid="14" id="jsRightBtn">
                         {% if has_fav_org %}已收藏{% else %}收藏{% endif %}
                    </div>
					<div class="clear">
						<ul>
                            <li>
                                <span>课 &nbsp;程&nbsp; 数：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  {{ course_cent.course_org.kcs }}</span>
                            </li>
                            <li>
                                <span>教 &nbsp;师&nbsp; 数：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  {{ course_cent.course_org.get_ls_sl }}</span>
                            </li>
							<li>所在地区：&nbsp;&nbsp;{{ course_cent.course_org.city }}</li>
							<li>认&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;证&nbsp;:
                                &nbsp;&nbsp;
								    <img title="金牌机构", src="{% static '/images/gold.png' %}"/>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
    <section>
	<div class="wp">
		<div class="list groupPurchase_detail_pro">
			<div class="left layout">
				<div class="head">
					<ul class="tab_header">
						<li class="active">课程详情</li>
					</ul>
				</div>
				<div class="tab_cont tab_cont1">

					<p>&nbsp; &nbsp; {{ course_cent.name }}</p><p>{% autoescape off %}{{ course_cent.detail }}{% endautoescape %} </p>

				</div>
				<div class="tab_cont tab_cont2" >
					<div class="comment">
						<div class="comenlist">

	                    </div>
					</div>
				</div>
			</div>
			<div class="right layout">
				<div class="head">相关课程推荐</div>
                <div class="group_recommend">
                    {% for tag in tag %}
                        <dl>
                            <dt>
                                <a target="_blank" href="{% url 'course_detail' tag.id %}">
                                    <img width="240" height="220" class="scrollLoading" src="../../Banner/{{ tag.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <a target="_blank" href="{% url 'course_detail' tag.id %}"><h2>{{ tag.name }}</h2></a>
                                <span class="fl">学习时长：<i class="key">{{ tag.learn_times }}</i></span>
                            </dd>
                        </dl>
                    {% endfor %}


                </div>
			</div>
		</div>
	</div>
</section>
{% endblock %}
{% block db_js %}
<script type="text/javascript">
//收藏分享
function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
        cache: false,
        type: "POST",
        url:"{% url 'add_fav' %}",
        data:{'fav_id':fav_id, 'fav_type':fav_type},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        },
        success: function(data) {
            if(data.status == 'fail'){
                if(data.msg == '用户未登录'){
                    window.location.href="{% url 'login' %}";
                }else{
                    alert(data.msg)
                }

            }else if(data.status == 'success'){
                current_elem.text(data.msg)
            }
        },
    });
}

$('#jsLeftBtn').on('click', function(){
    add_fav($(this), {{ course_cent.id }}, 1);
});

$('#jsRightBtn').on('click', function(){
    add_fav($(this), {{ course_cent.course_org.id }}, 2);
});
</script>
{% endblock %}

MxOnline/templates/org-detail-desc.html
{% extends 'org_base.html' %}
{% block custom_title %}机构介绍列表 {% endblock %}
{% block page_path %}机构介绍{% endblock %}
{% block right_form %}
<div class="right companycenter layout" >
        <div class="head">
            <h1>机构介绍</h1>
        </div>
        <div class="des">
                {{ course_org.desc }}
        </div>
    </div>
{% endblock %}

MxOnline/templates/org-detail-teachers.html
{% extends 'org_base.html' %}
{% block custom_title %}机构讲师列表 {% endblock %}
{% block page_path %}机构讲师{% endblock %}
{% block right_form %}
<div class="right companycenter layout" >
        <div class="head">
            <h1>机构讲师</h1>
        </div>
        <div class="messagelist">
            <div class=" butler_list butler-fav-box">
                {% for teachers_org  in teachers_org %}
                <dl class="des users">
                    <dt>
                        <a href="{% url 'teachers-detail' teachers_org.id %}">
                        <img width="100" height="100" class="scrollLoading" data-url="../../Banner/{{ teachers_org.image }}" src="../../Banner/{{ teachers_org.image }}"/>
                        </a>
                    </dt>
                    <dd>
                        <h1>
                            <a href="{% url 'teachers-detail' teachers_org.id %}">
                            {{ teachers_org.name }}<span class="key">已认证</span>
                            </a>
                        </h1>
                        <ul class="cont clearfix">
                            <li class="time">工作年限：<span>{{ teachers_org.work_years }}年</span></li>
                            <li class="c7">课程数：<span>{{ kctj2 }}</span></li>
                        </ul>
                    </dd>
                </dl>
                {% endfor %}

            </div>
        </div>
    </div>
{% endblock %}

MxOnline/templates/password_reset.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<title>密码修改</title>
	<link rel="stylesheet" type="text/css" href="{% static '/css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

<body>
<div class="wp">
    <div class="resetpassword" id="resetPwdForm">
        <h1>修改密码</h1>
        <p>{{ email }}已经通过验证，请设置新密码</p>
        <form id="reset_password_form" action="{% url 'modisp_pwd' %}" method="post">
            <ul>
                <li>
                    <input type="hidden" name="email" id="pwd" value="{{ email }}">
                    <input type="hidden" name="code" id="code" value="{{ code }}"
                    <i></i>
                </li>
                <li>
                    <span class="">新 密 码 ：</span>
                    <input type="password" name="password1" id="pwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <li>
                    <span class="">确定密码：</span>
                    <input type="password" name="password2" id="repwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>{% for key, erray in MoforPwdForm.errors.items %}{{erray}}{% endfor %}{{msg}}
                <li class="button">
                     <input class="btn btn-green" id="jsLoginBtn" type="submit" value="提交" />
                </li>
            </ul>
            {% csrf_token %}
        </form>
    </div>
    <div class="resetpassword" id="reset_password_tips" style="display:none;">
        <h1>修改密码成功,请重新登录</h1>
        <img class="fl" src="{% static '/images/check2.png' %}">
        <p class="successword">已经成功修改密码，请重新登录</p>
    </div>
</div>
</body>
</html>

MxOnline/templates/usercenter-info.html
{% extends 'usercenter_base.html' %}